import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadCatalog } from '../scripts/io';
const data=await loadCatalog();
const base=process.env.SITE_URL ?? 'http://127.0.0.1:4174/central-estudos-concursos/';
const destination=path.resolve(process.env.OUTPUT_DIR ?? 'test-results');
await mkdir(destination,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1360,height:900},locale:'pt-BR',timezoneId:'America/Sao_Paulo'});
const page=await context.newPage();
const errors:string[]=[];
page.on('pageerror',error=>errors.push(error.message));
const checks:string[]=[];
try {
  await page.clock.install({time:new Date('2026-09-24T15:00:00Z')});
  await page.goto(base);
  await expect(page.getByRole('heading',{level:1,name:'Continuar estudando'})).toBeVisible();
  const start=page.getByRole('button',{name:'Continuar estudando'});
  await expect(start).toBeEnabled();
  await page.screenshot({path:path.join(destination,'trilha-inicial.png'),fullPage:true});
  const dashboardAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(dashboardAxe.violations).toEqual([]);
  await start.click();
  await expect(page.getByRole('heading',{level:1})).toHaveText('Fundamentos de SQL — aprofundamento');
  await expect(page.locator('.tags').first()).toContainText('CRBio');
  await expect(page.locator('.tags').first()).toContainText('SETEC');
  const firstUrl=page.url();
  await page.reload();
  await expect(page.getByRole('heading',{level:1})).toHaveText('Fundamentos de SQL — aprofundamento');
  expect(page.url()).toBe(firstUrl);
  const activityAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(activityAxe.violations).toEqual([]);
  await page.getByRole('button',{name:'Concluir atividade',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Atividade concluída'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Atividade concluída'})).toBeVisible();
  await page.getByRole('button',{name:'Continuar',exact:true}).click();
  await expect(page.locator('.page-heading .eyebrow')).toContainText('REVISÃO');
  await page.getByRole('button',{name:'Concluir atividade',exact:true}).click();
  await page.getByRole('button',{name:'Continuar',exact:true}).click();
  await expect(page.locator('.page-heading .eyebrow')).toContainText('QUESTÕES');
  await expect(page.getByRole('button',{name:'Concluir atividade',exact:true})).toBeDisabled();
  const question=data.questions.find(q=>q.unitIds?.includes('TI-BD-003-01'))!;
  const wrong=question.options.find(o=>o.id!==question.answer)!;
  await page.getByRole('radio',{name:wrong.text,exact:true}).check();
  await page.getByRole('button',{name:'Conferir resposta'}).click();
  await expect(page.getByRole('heading',{name:'Vamos revisar este ponto'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Vamos revisar este ponto'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Conferir resposta'})).toHaveCount(0);
  await page.getByRole('button',{name:'Concluir atividade',exact:true}).click();
  await page.getByRole('button',{name:'Continuar',exact:true}).click();
  await expect(page.getByRole('heading',{level:1})).toHaveText('SELECT e expressões — aprofundamento');
  const secondUrl=page.url();
  await page.goto(base);
  await page.getByRole('button',{name:'Continuar estudando'}).click();
  await expect(page).toHaveURL(secondUrl);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:path.join(destination,'trilha-mobile.png')});
  checks.push('Entrada única, etapa 1 compartilhada, conclusão, D0, questão, erro, etapa 2 e retomada exata');
  await page.goto(`${base}#/erros`);
  await expect(page.getByRole('heading',{name:question.statement,exact:true})).toBeVisible();
  await page.goto(`${base}#/dados`);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Exportar meu progresso'}).click();
  const download=await downloadPromise;
  await download.saveAs(path.join(destination,'trilha-backup-test.json'));
  const {readFile}=await import('node:fs/promises');
  const backup=JSON.parse(await readFile(path.join(destination,'trilha-backup-test.json'),'utf8'));
  expect(backup.progress).toHaveLength(1);
  expect(backup.progress[0].id).toBe('TI-BD-003');
  expect(backup.progress[0].percent).toBe(4);
  expect(backup.attempts).toHaveLength(1);
  expect(backup.reviews.some((r:{stage:string;due:string})=>r.stage==='ERRO'&&r.due==='2026-09-26')).toBe(true);
  checks.push('IndexedDB: progresso parcial por ID único, tentativa sem duplicação, erro e revisão futura persistidos');
  await page.waitForFunction(()=>navigator.serviceWorker.ready.then(()=>true));
  await page.reload();
  await page.waitForFunction(()=>Boolean(navigator.serviceWorker.controller));
  await context.setOffline(true);
  await page.goto(base);
  await page.getByRole('button',{name:'Continuar estudando'}).click();
  await expect(page.getByRole('heading',{level:1})).toHaveText('SELECT e expressões — aprofundamento');
  checks.push('Retomada offline da atividade em andamento');
  expect(errors).toEqual([]);
  await writeFile(path.join(destination,'trail-verification.json'),JSON.stringify({base,at:new Date().toISOString(),checks,errors,accessibility:{dashboard:dashboardAxe.violations,activity:activityAxe.violations}},null,2));
  console.log(JSON.stringify({checks,errors}));
} finally {await browser.close();}
